version: '3.*'
services:
  slack_backend:
    container_name: som-backend
    build:
      context: .
      target: BASE
      args:
        - DEBUG_PORT=$DEBUG_PORT
    ports:
      - $PORT:$PORT
      - $DEBUG_PORT:$DEBUG_PORT
      - 5555:5555
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
