version: '3.*'
services:
  slack_backend:
    container_name: som-backend
    build:
      context: .
      target: BASE
      args:
        - DEBUG_PORT=$DEBUG_PORT
    ports:
      - $PORT:$PORT #app port
      - 9229:7876 #node port
      - 5555:5555 # prisma port
      - 5434:9229 #jest debug port
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
